### ISSUE TITLE
This doesn't use LSL at all, does it?

### ISSUE THREAD

**Issue by cboulay** [labstreaminglayer/App-XDFBrowser#1]
The CMakeLists and CI scripts for this repo reference LSL, but as far as I can tell that's just copied over from other repos. LSL isn't used by XDFBrowser at all, is it?

If xdf related items end up moving to the xdf-modules GitHub org then I'll probably move this tool there too. It can still be a submodule of the parent labstreaminglayer repo but I think maybe it doesn't belong there.

**Comment by mgrivich** [comment]
It doesn't reference LSL. I was the original author. I think all the commits by others have been fairly minor. I don't have any particular objection to it being moved, but I should have commit privileges on whichever repository it gets moved to.

**Comment by cboulay** [comment]
Of course! And I've added you to the xdf-modules org so you'll have access by default.
